language: node_js
node_js:
- '8'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/doc.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "F7zOUn/+bXWooWVShy6Xexi64qtU+mTS9Mn6V2Q9Ny14RgDKwbZHGqAxlm9yz7KGcbOEyjbJHGSvj+8OKwqCgMnub9gx9kE4ubF+Bq73n276DpW7NArXGvBJCBTjiO7TTpmmWXV6baQkY2Zw7G4a/luY5A4c1MlxAUoGzRt+oDGzPO9RTxU0U0nqzzHDyIVWU+E1jPOBi2usN9/i5i7lMK8ZZ2ZDOH+7ELPAdRUmKc43Di6ZaF0ZruJxCewYR5k44eaB80/Hh2agpMK9OYDuyrHz8pUfz4ihfzsIkTKfAgwYwGU6LyDfxUw1fW6aMFA8sLFKcKg2v4vpwBl672mWH1cRtI3YT5Rb7ZImy+aIFrIYqh7qRkjukQkzu1E/crGPco9/WNaW8xnW28e4/EWUXihnUk4f9Ex41Cniphzxq5zrNItn0ne0c926cKwcD23UX+AMMn7IRAX0/0ZzCGO9ejOEPjFeXkm9OHwnl09G26yiqi9wJ4xGxtzfG/CuI2yUedUnlV6UMvHX8lif0+IHpXOykzHKU0/RIu8SSw7ArWIUBo4d8suD8misSy7JQXMGE5UGiJNWQpnlQVlW/4pOSMyBU7EXq61OZVJmXJ3c6LImHYQjszoJc0h8WkNR1lJLRZdo3VxTsWXT3qqP0drqS+vod2fJAbjuFigAvP85dl8="
